const Sdata = [
    {   id: 1 ,
        sname: "DARK",
        imgsrc: "https://wallpapercave.com/wp/wp4056410.jpg",
        title : "Netflix Original Series",
        links : "https://www.netflix.com/in/browse/genre/839338",
    },
    {   id: 2,
        sname: "Stranger Things",
        imgsrc: "https://wallpapercave.com/wp/wp1917154.jpg",
        title: "Netflix Original Series",
        links: "https://www.netflix.com/in/title/80057281",
    },
    {   id: 3,
        sname: "Extra Curricular",
        imgsrc: "https://www.hitc.com/static/uploads/hitcn/1816/extracurricular_netflix_780_1544944.jpg",
        title: "Netflix Original Series",
        links: "https://www.netflix.com/in/browse/genre/839338",
    },
    {    id: 4,
        sname: "The Vampire Diaries",
        imgsrc: "https://images.justwatch.com/poster/8589251/s592",
        title: "Netflix Original Series",
        links: "https://www.netflix.com/in/browse/genre/839338",
    },
    {     id: 5,
        sname: "My First 2 Love",
        imgsrc: "https://i.pinimg.com/474x/7b/19/58/7b19584ec5ffba063a121508e78fe7a4.jpg",
        title: "Netflix Original Series",
        links: "https://www.netflix.com/in/browse/genre/839338",
    },
    {     id: 6,
        sname: "Extra Curricular",
        imgsrc: "https://www.hitc.com/static/uploads/hitcn/1816/extracurricular_netflix_780_1544944.jpg",
        title: "Netflix Original Series",
        links: "https://www.netflix.com/in/browse/genre/839338",
        status: "ok"
    },
];
export default Sdata;
